#!/bin/bash
# generate-homebrew-formula.sh
# Generates the Homebrew formula with DMG app bundle support.
# Run this after GoReleaser has published the release, so DMG SHA256s are available.
#
# Usage:
#   ./scripts/generate-homebrew-formula.sh <version> <tag>
#
# Example:
#   ./scripts/generate-homebrew-formula.sh 1.1.4 v1.1.4

set -euo pipefail

VERSION="${1:-}"
TAG="${2:-}"

if [[ -z "$VERSION" || -z "$TAG" ]]; then
    echo "Usage: $0 <version> <tag>"
    echo "Example: $0 1.1.4 v1.1.4"
    exit 1
fi

REPO="0xdps/daemon-hound"
RELEASE_URL="https://github.com/${REPO}/releases/download/${TAG}"

# Helper: compute SHA256 of a remote file with retries
remote_sha256() {
    local url="$1"
    local max_retries=10
    local retry_delay=3
    local attempt=1

    while [[ $attempt -le $max_retries ]]; do
        if sha=$(curl -fsSL "$url" 2>/dev/null | shasum -a 256 | awk '{print $1}'); then
            echo "$sha"
            return 0
        fi
        echo "Retry $attempt/$max_retries: $url" >&2
        sleep $retry_delay
        attempt=$((attempt + 1))
    done

    echo "Failed to fetch $url after $max_retries attempts" >&2
    return 1
}

echo "Fetching SHA256s for release ${TAG}..." >&2

# Tarball SHA256s (used for all platforms)
DARWIN_X86_TGZ_SHA=$(remote_sha256 "${RELEASE_URL}/daemon-hound_${VERSION}_Darwin_x86_64.tar.gz")
DARWIN_ARM_TGZ_SHA=$(remote_sha256 "${RELEASE_URL}/daemon-hound_${VERSION}_Darwin_arm64.tar.gz")
LINUX_X86_TGZ_SHA=$(remote_sha256 "${RELEASE_URL}/daemon-hound_${VERSION}_Linux_x86_64.tar.gz")
LINUX_ARM_TGZ_SHA=$(remote_sha256 "${RELEASE_URL}/daemon-hound_${VERSION}_Linux_arm64.tar.gz")

# DMG SHA256s (macOS only, for the signed app bundle)
DARWIN_X86_DMG_SHA=$(remote_sha256 "${RELEASE_URL}/daemon-hound_${VERSION}_macOS_x86_64.dmg")
DARWIN_ARM_DMG_SHA=$(remote_sha256 "${RELEASE_URL}/daemon-hound_${VERSION}_macOS_arm64.dmg")

cat <<EOF
# typed: false
# frozen_string_literal: true

# This file was generated by scripts/generate-homebrew-formula.sh. DO NOT EDIT.
class DaemonHound < Formula
  desc "Opinionated local config and secret management for developers"
  homepage "https://github.com/0xdps/daemon-hound"
  version "${VERSION}"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "${RELEASE_URL}/daemon-hound_${VERSION}_Darwin_x86_64.tar.gz"
      sha256 "${DARWIN_X86_TGZ_SHA}"

      resource "app_bundle" do
        url "${RELEASE_URL}/daemon-hound_${VERSION}_macOS_x86_64.dmg"
        sha256 "${DARWIN_X86_DMG_SHA}"
      end
    end
    if Hardware::CPU.arm?
      url "${RELEASE_URL}/daemon-hound_${VERSION}_Darwin_arm64.tar.gz"
      sha256 "${DARWIN_ARM_TGZ_SHA}"

      resource "app_bundle" do
        url "${RELEASE_URL}/daemon-hound_${VERSION}_macOS_arm64.dmg"
        sha256 "${DARWIN_ARM_DMG_SHA}"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "${RELEASE_URL}/daemon-hound_${VERSION}_Linux_x86_64.tar.gz"
      sha256 "${LINUX_X86_TGZ_SHA}"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "${RELEASE_URL}/daemon-hound_${VERSION}_Linux_arm64.tar.gz"
      sha256 "${LINUX_ARM_TGZ_SHA}"
    end
  end

  def install
    # Install the raw binary first (fallback for all platforms)
    bin.install "dhd"

    # On macOS, also install the signed app bundle from the DMG
    if OS.mac?
      resource("app_bundle").stage do |staging|
        dmg_file = Dir["*.dmg"].first
        if dmg_file
          # Mount the DMG
          mount_point = \`hdiutil attach #{dmg_file.shellescape} -nobrowse -readonly 2>&1 | tail -1 | awk '{print \$NF}'\`.strip
          if mount_point && !mount_point.empty? && File.exist?(mount_point)
            app_src = File.join(mount_point, "DaemonHound.app")
            if File.exist?(app_src)
              # Install the signed app bundle to the prefix
              prefix.install Dir["#{app_src}"]

              # Replace the raw binary symlink with one pointing to the signed bundle
              rm_f bin/"dhd"
              bin.install_symlink prefix/"DaemonHound.app/Contents/MacOS/dhd" => "dhd"
            end
            # Unmount the DMG
            system "hdiutil", "detach", mount_point
          end
        end
      end
    end
  end

  def post_install
    if OS.mac?
      # Auto-create symlink in ~/Applications so the signed bundle is
      # discoverable by dhd daemon install and shows up in Launchpad.
      app_bundle = opt_prefix/"DaemonHound.app"
      applications_dir = Pathname.new("~/Applications").expand_path
      if app_bundle.exist? && applications_dir.exist?
        ln_sf app_bundle, applications_dir/"DaemonHound.app"
      end
    end
  end

  def caveats
    if OS.mac?
      <<~EOS
        DaemonHound has been installed with the signed app bundle.

        The signed app bundle is located at:
          #{opt_prefix}/DaemonHound.app

        A symlink has been created in your Applications folder:
          ~/Applications/DaemonHound.app

        The CLI binary \`dhd\` is symlinked to the signed bundle's executable.
      EOS
    else
      <<~EOS
        DaemonHound has been installed.

        Run \`dhd init\` to get started.
      EOS
    end
  end

  test do
    system "#{bin}/dhd", "--version"
  end
end
EOF
